server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
    host: localhost
    port: 13001
    coordinatorExchangeSvrList: coordinators
    prometheus: PROMETHEUS_URL
    monitor:
      executor:
        heapAlarmThreshold: 80
        logPath: logPath
      instance:
        exportPort: 19100
        cpuAlarmThreshold: 70
        memAlarmThreshold: 70
        diskAlarmThreshold: 90

spring:
    datasource:
        url: jdbc:mysql://localhost:3307/information_schema?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
        username: root
        password: 123123
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
