cluster:
    name: dingo

coordinator:
    server:
        port: 19181
    raft:
        group:
            id: COORDINATOR_RAFT
        port: 9181
        servers: localhost:9181
    options:
        fake: false
        initCoordinatorSrvList: localhost:9181
        raftGroupId: COORDINATOR_RAFT
        cliOptions:
            timeoutMs: 10000
            maxRetry: 3
            rpcProcessorThreadPoolSize: 4
executor:
    server:
        port: 19191

client:
    coordinator:
        servers: localhost:19181
    executor:
        servers: localhost:19191

instance.host: localhost

data.dir: /opt/dingo/data

store:
    initialServerList: localhost:10181
    failoverRetries: 10
    engine:
        options:
            raftDataPath: /opt/dingo/data/executor/raft
            rocksDBOptions:
                dbPath: /opt/dingo/data/executor/db
            serverAddress:
                ip: localhost
                port: 10181
            regionEngineOptionsList:
                - { regionId: 1, endKey: "1000000", nodeOptions: { timerPoolSize: 1, rpcProcessorThreadPoolSize: 4 } }
                - { regionId: 2, startKey: "1000000", nodeOptions: { timerPoolSize: 1, rpcProcessorThreadPoolSize: 4 } }
