cluster:
    name: dingo_demo
    executor:
        port: 19191
    coordinator:
        raft:
            servers: localhost:19181

instance:
    host: localhost

data:
    dir: dingo/data

store:
    initialServerList: localhost:10181
    failoverRetries: 10
    engine:
        options:
            raftDataPath: dingo/executor/raft
            rocksDBOptions:
                dbPath: dingo/executor/db
            serverAddress:
                ip: localhost
                port: 10181
            regionEngineOptionsList:
                - { regionId: 1, endKey: "1000000", nodeOptions: { timerPoolSize: 1, rpcProcessorThreadPoolSize: 4 } }
                - { regionId: 2, startKey: "1000000", nodeOptions: { timerPoolSize: 1, rpcProcessorThreadPoolSize: 4 } }

coordinator:
    options:
        fake: false
        pdGroupId: pdCluster-1
        initCoordinatorSrvList: localhost:9181
        raftGroupId: COORDINATOR_RAFT
        cliOptions:
            timeoutMs: 10000
            maxRetry: 3
            rpcProcessorThreadPoolSize: 4
