cluster.name: dingo_demo
cluster.coordinator.name: coordinator-resource
cluster.coordinator.tag: coordinator-tag
cluster.coordinator.replicas: 3
cluster.coordinator.partitions: 1

instance.host: executor
zookeeper.servers: zookeeper:2181

controller.name: dingo_controller
controller.mode: STANDALONE

server.coordinator.port: 19181
server.executor.port: 19191

store.default.replicas: 3
store.default.partitions: 3
data.dir: /opt/dingo/data

store.cluster.id: 1
store.cluster.name: dingo_kv_cluster
store.initialServerList: localhost:10181
store.failoverRetries: 10
store.futureTimeoutMillis: 30000
coordinator.options.fake: false
coordinator.options.raftGroupId: pdCluster-1
coordinator.options.initCoordinatorSrvList: localhost:9180
coordinator.options.cliOptions.timeoutMs: 10000
coordinator.options.cliOptions.maxRetry: 3
store.engine.options.raftDataPath: temp_rhea_raft/
store.engine.options.rocksDBOptions.dbPath: temp_rhea_db/
store.engine.options.serverAddress.ip: localhost
store.engine.options.serverAddress.port: 10181
store.engine.options.regionEngineOptionsList:
    - { regionId: 1, endKey: "1000000", nodeOptions: { timerPoolSize: 1, rpcProcessorThreadPoolSize: 4 } }
    - { regionId: 2, startKey: "1000000", nodeOptions: { timerPoolSize: 1, rpcProcessorThreadPoolSize: 4 } }
