// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum.proto

package io.dingodb.raft.entity;

public final class EnumOutter {
  private EnumOutter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code raft.EntryType}
   */
  public enum EntryType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ENTRY_TYPE_UNKNOWN = 0;</code>
     */
    ENTRY_TYPE_UNKNOWN(0),
    /**
     * <code>ENTRY_TYPE_NO_OP = 1;</code>
     */
    ENTRY_TYPE_NO_OP(1),
    /**
     * <code>ENTRY_TYPE_DATA = 2;</code>
     */
    ENTRY_TYPE_DATA(2),
    /**
     * <code>ENTRY_TYPE_CONFIGURATION = 3;</code>
     */
    ENTRY_TYPE_CONFIGURATION(3),
    /**
     * <code>ENTRY_TYPE_MSG = 4;</code>
     */
    ENTRY_TYPE_MSG(4),
    ;

    /**
     * <code>ENTRY_TYPE_UNKNOWN = 0;</code>
     */
    public static final int ENTRY_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <code>ENTRY_TYPE_NO_OP = 1;</code>
     */
    public static final int ENTRY_TYPE_NO_OP_VALUE = 1;
    /**
     * <code>ENTRY_TYPE_DATA = 2;</code>
     */
    public static final int ENTRY_TYPE_DATA_VALUE = 2;
    /**
     * <code>ENTRY_TYPE_CONFIGURATION = 3;</code>
     */
    public static final int ENTRY_TYPE_CONFIGURATION_VALUE = 3;
    /**
     * <code>ENTRY_TYPE_MSG = 4;</code>
     */
    public static final int ENTRY_TYPE_MSG_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EntryType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EntryType forNumber(int value) {
      switch (value) {
        case 0: return ENTRY_TYPE_UNKNOWN;
        case 1: return ENTRY_TYPE_NO_OP;
        case 2: return ENTRY_TYPE_DATA;
        case 3: return ENTRY_TYPE_CONFIGURATION;
        case 4: return ENTRY_TYPE_MSG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EntryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EntryType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EntryType>() {
            public EntryType findValueByNumber(int number) {
              return EntryType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.dingodb.raft.entity.EnumOutter.getDescriptor().getEnumTypes().get(0);
    }

    private static final EntryType[] VALUES = values();

    public static EntryType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EntryType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:raft.EntryType)
  }

  /**
   * Protobuf enum {@code raft.ErrorType}
   */
  public enum ErrorType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ERROR_TYPE_NONE = 0;</code>
     */
    ERROR_TYPE_NONE(0),
    /**
     * <code>ERROR_TYPE_LOG = 1;</code>
     */
    ERROR_TYPE_LOG(1),
    /**
     * <code>ERROR_TYPE_STABLE = 2;</code>
     */
    ERROR_TYPE_STABLE(2),
    /**
     * <code>ERROR_TYPE_SNAPSHOT = 3;</code>
     */
    ERROR_TYPE_SNAPSHOT(3),
    /**
     * <code>ERROR_TYPE_STATE_MACHINE = 4;</code>
     */
    ERROR_TYPE_STATE_MACHINE(4),
    /**
     * <code>ERROR_TYPE_META = 5;</code>
     */
    ERROR_TYPE_META(5),
    ;

    /**
     * <code>ERROR_TYPE_NONE = 0;</code>
     */
    public static final int ERROR_TYPE_NONE_VALUE = 0;
    /**
     * <code>ERROR_TYPE_LOG = 1;</code>
     */
    public static final int ERROR_TYPE_LOG_VALUE = 1;
    /**
     * <code>ERROR_TYPE_STABLE = 2;</code>
     */
    public static final int ERROR_TYPE_STABLE_VALUE = 2;
    /**
     * <code>ERROR_TYPE_SNAPSHOT = 3;</code>
     */
    public static final int ERROR_TYPE_SNAPSHOT_VALUE = 3;
    /**
     * <code>ERROR_TYPE_STATE_MACHINE = 4;</code>
     */
    public static final int ERROR_TYPE_STATE_MACHINE_VALUE = 4;
    /**
     * <code>ERROR_TYPE_META = 5;</code>
     */
    public static final int ERROR_TYPE_META_VALUE = 5;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ErrorType forNumber(int value) {
      switch (value) {
        case 0: return ERROR_TYPE_NONE;
        case 1: return ERROR_TYPE_LOG;
        case 2: return ERROR_TYPE_STABLE;
        case 3: return ERROR_TYPE_SNAPSHOT;
        case 4: return ERROR_TYPE_STATE_MACHINE;
        case 5: return ERROR_TYPE_META;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorType>() {
            public ErrorType findValueByNumber(int number) {
              return ErrorType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.dingodb.raft.entity.EnumOutter.getDescriptor().getEnumTypes().get(1);
    }

    private static final ErrorType[] VALUES = values();

    public static ErrorType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:raft.ErrorType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nenum.proto\022\004raft*\200\001\n\tEntryType\022\026\n\022ENTR" +
      "Y_TYPE_UNKNOWN\020\000\022\024\n\020ENTRY_TYPE_NO_OP\020\001\022\023" +
      "\n\017ENTRY_TYPE_DATA\020\002\022\034\n\030ENTRY_TYPE_CONFIG" +
      "URATION\020\003\022\022\n\016ENTRY_TYPE_MSG\020\004*\227\001\n\tErrorT" +
      "ype\022\023\n\017ERROR_TYPE_NONE\020\000\022\022\n\016ERROR_TYPE_L" +
      "OG\020\001\022\025\n\021ERROR_TYPE_STABLE\020\002\022\027\n\023ERROR_TYP" +
      "E_SNAPSHOT\020\003\022\034\n\030ERROR_TYPE_STATE_MACHINE" +
      "\020\004\022\023\n\017ERROR_TYPE_META\020\005B$\n\026io.dingodb.ra" +
      "ft.entityB\nEnumOutter"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
