spring:
    application:
        name: dingodb-manager
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
  host: 127.0.0.1
  port: 13000
  coordinatorExchangeSvrList: zserver:30013
  grpc:
    port: 9999
security:
    cipher:
        keyPath: /opt/dingo/conf/dingodb.jks
        keyPass: dingodb
        storePass: dingodb
        alias: dingodb
        issuer: dingo
    verify: true
