spring:
    application:
        name: dingodb-manager
    profiles:
        active: dev
security:
    cipher:
        keyPath: /opt/dingo/conf/dingodb.jks
        keyPass: dingodb
        storePass: dingodb
        alias: dingodb
        issuer: dingo
    verify: true
