cluster:
    name: dingo
exchange:
    host: HOSTNAME
    port: 8765
server:
    coordinators: COORDINATORS
    user: user
    keyring: TO_BE_CONTINUED
    resourceTag: 1
    mysqlPort: 3307
variable:
    autoIncrementCacheCount: 100
    autoIncrementIncrement: 1
    autoIncrementOffset: 1
