cluster:
    name: dingo
exchange:
    host: HOSTNAME
    port: 8765
server:
    coordinators: COORDINATORS
    user: user
    keyring: TO_BE_CONTINUED
    resourceTag: 1
    mysqlPort: 3307
variable:
    autoIncrementCacheCount: 100
    autoIncrementIncrement: 1
    autoIncrementOffset: 1
common:
    scheduledCoreThreads: 16
    lockCoreThreads: 0
    globalCoreThreads: 0
store:
    bufferSize: 67108864
    bufferNumber: 2
    fileSize: 67108864
security:
    ldap:
        ldapHost: ldap
        ldapPort: 389
        bindDN: cn=admin,dc=localdomain,dc=com
        password: 123456
        baseDN: dc=localdomain,dc=com
    cipher:
        keyPath: /opt/dingo/conf/dingodb.jks
        keyPass: dingodb
        storePass: dingodb
        alias: dingodb
        issuer: dingo
