cluster:
    name: dingo
exchange:
    host: XXXXXX
    port: 19191
server:
    coordinatorExchangeSvrList: coordinator3:19181,coordinator2:19181,coordinator1:19181
    dataPath: /opt/dingo/executor/meta
store:
    dbPath: /opt/dingo/executor/raftDb
    raft:
        port: 9191
        raftPath: /opt/dingo/executor/raftLog
    collectStatsInterval: 5
