cluster.name: dingo_demo
cluster.coordinator.name: coordinator-resource
cluster.coordinator.tag: coordinator-tag
cluster.coordinator.replicas: 3
cluster.coordinator.partitions: 1
cluster.coordinator.raft.servers: localhost:19181
cluster.coordinator.raft.data.dir: dingo/data

instance.host: localhost
zookeeper.servers: 172.20.3.83:2181

controller.name: dingo_controller
controller.mode: STANDALONE

server.coordinator.port: 19181
server.executor.port: 19191

cluster.coordinator.raft.port: 9181

default.replicas: 3
default.partitions: 3
data.dir: dingo/data
store.default.replicas: 3
store.default.partitions: 3
data.dir: /root/work/dingo/data

store.cluster.id: 1
store.cluster.name: dingo_kv_cluster
store.initialServerList: server:10181,server2:10181,server3:10181
store.failoverRetries: 10
store.futureTimeoutMillis: 30000
coordinator.options.fake: false
coordinator.options.raftGroupId: pdCluster-1
coordinator.options.initCoordinatorSrvList: server:9180,server2:9180,server3:9180
coordinator.options.cliOptions.timeoutMs: 10000
coordinator.options.cliOptions.maxRetry: 3
store.engine.options.raftDataPath: temp_rhea_raft/
store.engine.options.rocksDBOptions.dbPath: temp_rhea_db/
store.engine.options.serverAddress.ip: server
store.engine.options.serverAddress.port: 10181
store.engine.options.regionEngineOptionsList:
    - { regionId: 1, endKey: "1000000", nodeOptions: { timerPoolSize: 1, rpcProcessorThreadPoolSize: 4 } }
    - { regionId: 2, startKey: "1000000", nodeOptions: { timerPoolSize: 1, rpcProcessorThreadPoolSize: 4 } }
